package edu.poly.common;

public enum PageType {
	INDEX_MANAGEMENT_PAGE, USER_MANAGEMENT_PAGE, REPORT_MANAGEMENT_PAGE, VIDEO_MANAGEMENT_PAGE,
	LOGIN_MANAGEMENT_PAGE, HOME_MANAGEMENT_PAGE,
	SITE_HOME_PAGE, SITE_FAVORITES_PAGE, SITE_FORGOTPASS_PAGE,
	SITE_UPDATEACCOUNT_PAGE, SITE_DETAIL_PAGE, SITE_LOGIN_PAGE,
	SITE_REGISTER_PAGE, SITE_CHANGEPASSWORD_PAGE, SITE_SHAREVIDEO_PAGE
}
